CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
                              GENRE_ID BIGINT NOT NULL AUTO_INCREMENT,
                              GENRE_NAME CHARACTER VARYING(50),
                              CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_GENRE_ID ON PUBLIC.GENRE (GENRE_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
                            MPA_ID BIGINT NOT NULL AUTO_INCREMENT,
                            MPA_NAME CHARACTER VARYING(50),
                            CONSTRAINT MPA_PK PRIMARY KEY (MPA_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_MPA_ID ON PUBLIC.MPA (MPA_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
                             FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
                             FILM_NAME CHARACTER VARYING(100) NOT NULL,
                             FILM_DESCRIPTION CHARACTER VARYING(255),
                             FILM_RELEASEDATE DATE,
                             FILM_DURATION BIGINT,
                             RATING_ID BIGINT,
                             CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID)
);
CREATE INDEX IF NOT EXISTS FILM_MPA_FK_INDEX_2 ON PUBLIC.FILM (RATING_ID);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_FILM_ID ON PUBLIC.FILM (FILM_ID);
-- PUBLIC.FILM foreign keys
ALTER TABLE PUBLIC.FILM ADD CONSTRAINT IF NOT EXISTS FILM_MPA_FK FOREIGN KEY (RATING_ID) REFERENCES PUBLIC.MPA(MPA_ID) ON DELETE SET NULL ON UPDATE RESTRICT;

CREATE TABLE IF NOT EXISTS PUBLIC."USER" (
                               USER_ID BIGINT NOT NULL AUTO_INCREMENT,
                               USER_EMAIL CHARACTER VARYING(50),
                               USER_LOGIN CHARACTER VARYING(50) NOT NULL,
                               USER_NAME CHARACTER VARYING(50) NOT NULL,
                               USER_BIRTHDAY DATE,
                               CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_USER_ID ON PUBLIC."USER" (USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRES (
                                    FILM_ID BIGINT NOT NULL,
                                    GENRE_ID BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS FILM_GENRES_FILM_FK_INDEX_C ON PUBLIC.FILM_GENRES (FILM_ID);
CREATE INDEX IF NOT EXISTS FILM_GENRES_GENRE_FK_INDEX_C ON PUBLIC.FILM_GENRES (GENRE_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
                                   FILM_ID BIGINT NOT NULL,
                                   USER_ID BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS FILM_LIKES_FILM_FK_INDEX_7 ON PUBLIC.FILM_LIKES (FILM_ID);
CREATE INDEX IF NOT EXISTS FILM_LIKES_USER_FK_INDEX_7 ON PUBLIC.FILM_LIKES (USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIEND (
                               ADDING_USER_ID BIGINT,
                               ADDED_USER_ID BIGINT,
                               ISACCEPTED BOOLEAN
);
CREATE INDEX IF NOT EXISTS FRIEND_FILM_FK_1_INDEX_7 ON PUBLIC.FRIEND (ADDED_USER_ID);
CREATE INDEX IF NOT EXISTS FRIEND_FILM_FK_INDEX_7 ON PUBLIC.FRIEND (ADDING_USER_ID);